services:
  nginx:
    image: nginx:latest
    volumes:
      - ./volumes/logs/nginx:/var/log/nginx
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
      - ./dockerfiles/nginx/snippets:/etc/nginx/snippets
    depends_on:
      - web
    networks:
      - proxy-network
      - default
    restart: always
  web:
    image: joshting1999/random-chat:v1.0.0
    volumes:
      - ./volumes/logs/php:/var/log/php  # ← 掛載 PHP-FPM log 目錄
    depends_on:
      - mysql
      - redis
    restart: always

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./volumes/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Taipei
    restart: unless-stopped  

  soketi:
    image: quay.io/soketi/soketi:latest
    environment:
      - SOKETI_DEBUG=1
      - SOKETI_METRICS_SERVER_PORT=9601
      - SOKETI_DEFAULT_APP_ID=${PUSHER_APP_ID}
      - SOKETI_DEFAULT_APP_KEY=${PUSHER_APP_KEY}
      - SOKETI_DEFAULT_APP_SECRET=${PUSHER_APP_SECRET}
      - SOKETI_DEFAULT_APP_NAME=${APP_NAME}
      - SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES=true
      - SOKETI_DEFAULT_APP_ENABLE_STATS=true
    restart: unless-stopped

  redis:
    image: redis:latest
    volumes:
      - ./volumes/data/redis:/data
    restart: always

networks:
  proxy-network:
    external: true
    driver: bridge